name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run build with Gradle wrapper
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: modjar
          path: build/libs/*.jar

